language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate
notifications:
  slack:
    secure: RT0QfwJTi72/XLiSbQgr8Ezg/PFmyq6Xb0SVX8jXGuX3D+4lXk02bBePtLJ7AlWDOoUDW1YpJpOzHYXgb1/y+wWfczU0Z1t+s89mcvRbHiVOMl07M1pI0ChGJJdRCpKYuEIkQnmH66XDDQ1dKP3SaVo1FdALMlVPK476VRt3BfJ/g3tFfUkR+WS6Lw1TxcKGr5MPqcMuDwtIdeR/y+dQJFNrVcUu4487gZ/xsz3eCryHdFGKGQyiCaGiqU7ny1plVavJLHGlUgukk5uXjwIb/ESy1SuZawF0kxZBw97yPXJX48eHS7c2qIQUjpNGrotelv1RKOOSFJJAdt7mZTSTyDtHlDRt9K9wxw7vHKnKtwfd0JTjXIJHswsi3pjGprGNTB2xJDW9T53NaKU5SmFRoVTiauO+YrfZYdoh7s3u28M2axXZXoYpnaB/V1fVCglG6Qs79+Tz7u8tKkO94511qVznItAjaN6z1zqZxxFQ86LynE1RIY1osHQu06MUrNq013Owf13CcXyhGXgfL0KtPB/bpzVLBaEllMOTiDjP/gInHOxxEziUwNHwYDXFKSWf7uT9VdqAQV0ZCtlK27/98AWpdMbiuYkxgrDtMEQoYEaFr4a4vAn69biiD3lY6rw1P+8OeVE7tq+3rQyDAbSTe6xOG6Vx3f1DatTWqO+h5Us=
